### ISSUE TITLE
Testing pet shop transaction results in Error

### ISSUE THREAD

**Issue by ddelmoli** [trufflesuite/trufflesuite.github.io#176]
Error: the tx doesn't have the correct nonce. account has nonce of: 14 tx has nonce of: 20

**Comment by kwv** [comment]
just hit this myself.   It appears to be addressed if you also run `truffle deploy` per  https://github.com/trufflesuite/trufflesuite.github.io/issues/176

**Comment by bmmpxf** [comment]
Hi @ddelmoli . We've done a big update of the tutorial since your issue was raised, and so this should not occur now.

I'm closing this, but if you still encounter issues, please feel free to raise a new one on our new website repo: https://github.com/trufflesuite/trufflesuite.com/issues (we've moved). Thanks!
